/**
 * Generates IRLY app icons and splash assets from the brand mark geometry
 * (same proportions as src/brand/IrlyMark.tsx).
 *
 *   node scripts/make-icons.mjs        (requires `sharp`)
 */
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
let sharp;
try {
  sharp = require('sharp');
} catch {
  sharp = require('/opt/npm-tools/node_modules/sharp');
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = (f) => join(root, 'assets', f);
mkdirSync(join(root, 'assets'), { recursive: true });

const BG = '#08080C';
const BRAND = '#8B6CFF';

/** Mark SVG: two rings and their lens. `w` is the mark width in px. */
function mark({ size, w, ring = '#FFFFFF', lens = BRAND, glow = false }) {
  const d = w / 1.58;
  const sep = d * 0.58;
  const r = d / 2;
  const stroke = Math.max(2, d * 0.075);
  const cx = size / 2;
  const cy = size / 2;
  const ax = cx - sep / 2;
  const bx = cx + sep / 2;
  return `
    <defs>
      <clipPath id="a"><circle cx="${ax}" cy="${cy}" r="${r}"/></clipPath>
      <radialGradient id="g" cx="50%" cy="50%" r="50%">
        <stop offset="0" stop-color="${lens}" stop-opacity="0.45"/>
        <stop offset="1" stop-color="${lens}" stop-opacity="0"/>
      </radialGradient>
    </defs>
    ${glow ? `<circle cx="${cx}" cy="${cy}" r="${d * 1.05}" fill="url(#g)"/>` : ''}
    <circle cx="${bx}" cy="${cy}" r="${r}" fill="${lens}" clip-path="url(#a)"/>
    <circle cx="${ax}" cy="${cy}" r="${r - stroke / 2}" fill="none" stroke="${ring}" stroke-width="${stroke}"/>
    <circle cx="${bx}" cy="${cy}" r="${r - stroke / 2}" fill="none" stroke="${ring}" stroke-width="${stroke}"/>`;
}

function svg(size, body, bg) {
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
      ${bg ? `<defs><linearGradient id="bgg" x1="0" y1="0" x2="0.4" y2="1"><stop offset="0" stop-color="#17113A"/><stop offset="0.55" stop-color="${BG}"/><stop offset="1" stop-color="${BG}"/></linearGradient></defs><rect width="${size}" height="${size}" fill="url(#bgg)"/>` : ''}
      ${body}
    </svg>`,
  );
}

async function png(file, size, body, bg) {
  await sharp(svg(size, body, bg)).png().toFile(out(file));
  console.log('wrote', file);
}

await png('icon.png', 1024, mark({ size: 1024, w: 620, glow: true }), true);
await png('splash-icon.png', 1024, mark({ size: 1024, w: 870 }), false);
await png('android-icon-foreground.png', 1024, mark({ size: 1024, w: 520 }), false);
await png('android-icon-monochrome.png', 1024, mark({ size: 1024, w: 520, lens: '#FFFFFF' }), false);
await sharp({ create: { width: 1024, height: 1024, channels: 4, background: BG } }).png().toFile(out('android-icon-background.png'));
console.log('wrote android-icon-background.png');
await png('favicon.png', 96, mark({ size: 96, w: 80 }), true);

writeFileSync(out('.generated'), 'Generated by scripts/make-icons.mjs\n');
