// Generated by .github/scripts/dubai-media.mjs: photo keys whose picture is now a Dubai photo
// (Pixabay or Pexels, served from the photo library). Do not edit by hand.
export const DUBAI_KEYS: readonly string[] = [];
