// Generated by .github/scripts/pexels.mjs: photo keys whose picture is a Dubai photo from Pexels
// (served from the photo library). Do not edit by hand.
export const PEXELS_KEYS: readonly string[] = [];
